# -*- coding: utf-8 -*-
"""ml2021.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRUvhlfULaYqgjNrUvRNxMxTH3BEMriT
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

RANDOM_STATE = 42

# -----------------------------
# 1. Load data
# -----------------------------
train = pd.read_csv('/content/train.csv')  # adjust path if needed

TARGET_COL = "tested_positive3"

# -----------------------------
# 2. Prepare features
# -----------------------------
X = train.drop(columns=["id", TARGET_COL])
y = train[TARGET_COL]

# -----------------------------
# 3. Split
# -----------------------------
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify= None
)

# -----------------------------
# 4. Pipeline: Scaling + Feature Selection + Linear Regression
# -----------------------------
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("select", SelectKBest(
        score_func=f_regression,
        k=min(20, X_train.shape[1])  # keep top 20 or fewer
    )),
    ("lr", LinearRegression())
])

# -----------------------------
# 5. Train
# -----------------------------
pipeline.fit(X_train, y_train)

# -----------------------------
# 6. Predict
# -----------------------------
rmse = root_mean_squared_error(y_val, pipeline.predict(X_val))
print(f"Our RMSE: {rmse:.5f}")