# -*- coding: utf-8 -*-
"""explic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GTNn6BwIPhSfo3DSGWzrpI5kZAn36Bm
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import FeatureUnion
from sklearn.metrics import f1_score

# -----------------------
# Load data
# -----------------------
train = pd.read_csv("/content/train.csv")  # adjust path if needed

# Fill missing values
for col in ["url", "title"]:
    train[col] = train[col].fillna("")

# Combine url and title
train["text"] = train["url"] + " " + train["title"]

X = train["text"]
y = train["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=None
)

# -----------------------
# TF-IDF features
# -----------------------
word_tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=100_000,
    min_df=2,
    analyzer="word"
)

char_tfidf = TfidfVectorizer(
    ngram_range=(3, 5),
    max_features=100_000,
    analyzer="char"
)

vectorizer = FeatureUnion([
    ("word_tfidf", word_tfidf),
    ("char_tfidf", char_tfidf),
])

# -----------------------
# Model
# -----------------------
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    n_jobs=-1
)

# -----------------------
# Training
# -----------------------
X_train_vec = vectorizer.fit_transform(X_train)

model.fit(X_train_vec, y_train)

# -----------------------
# Predict test
# -----------------------
X_test_vec = vectorizer.transform(X_test)
test_preds = model.predict(X_test_vec)
print(f"Our metric: {f1_score(y_test, test_preds):.5f}")