# -*- coding: utf-8 -*-
"""multilabel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trZ5UVQb01UspZUVBYQDTM3Cy0EDQQ3K
"""

import os, cv2, numpy as np, pandas as pd, scipy.sparse as sp
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import f1_score
from xgboost import XGBClassifier

# -------------------------
# Reproducibility
# -------------------------
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# --------------------
# Our split
# --------------------
df = pd.read_csv('/content/train.csv')  # adjust path if needed
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

IMAGE_DIR = "/content/data"  # adjust path if needed

# -------------------------
# Label processing
# -------------------------
train_df["Labels_list"] = train_df["Labels"].apply(lambda x: list(map(int, x.split())))
mlb = MultiLabelBinarizer(classes=list(range(1, 20)))  # label 12 kept empty
y = mlb.fit_transform(train_df["Labels_list"])

# -------------------------
# Image feature extraction
# -------------------------
def extract_image_features(path):
    img = cv2.imread(path)
    if img is None:
        return np.zeros(110)

    img = cv2.resize(img, (256, 256))
    h, w, _ = img.shape
    feats = []

    # RGB histograms
    for c in range(3):
        hist = cv2.calcHist([img], [c], None, [32], [0, 256])
        feats.extend(cv2.normalize(hist, hist).flatten())

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 100, 200)

    feats += [
        gray.mean(), gray.std(), gray.min(), gray.max(),
        edges.mean(),
        h, w, h / w
    ]
    return np.array(feats)

X_img = np.vstack([
    extract_image_features(os.path.join(IMAGE_DIR, img))
    for img in train_df["ImageID"]
])

# -------------------------
# Caption TF-IDF
# -------------------------
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=3,
    stop_words="english"
)
X_txt = tfidf.fit_transform(train_df["Caption"])

# -------------------------
# Combine features
# -------------------------
X = sp.hstack([sp.csr_matrix(X_img), X_txt])

# -------------------------
# XGBoost (multi-label)
# -------------------------
xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    random_state=RANDOM_STATE
)

model = OneVsRestClassifier(xgb, n_jobs=-1)
model.fit(X, y)

# -------------------------
# Test prediction
# -------------------------
X_test_img = np.vstack([
    extract_image_features(os.path.join(IMAGE_DIR, img))
    for img in test_df["ImageID"]
])
X_test_txt = tfidf.transform(test_df["Caption"])
X_test = sp.hstack([sp.csr_matrix(X_test_img), X_test_txt])

test_pred = (model.predict_proba(X_test) >= 0.5).astype(int)

test_df["Labels_list"] = test_df["Labels"].apply(parse_labels)
y_test = mlb.fit_transform(test_df["Labels_list"])

print(f"Our score: {fbeta_score(y_test, test_pred, beta=1.0, average="micro", zero_division=0):.5f}")