# -*- coding: utf-8 -*-
"""wids.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xR4so515zgHKC-ldWA0roIpTLBTVrmhM
"""

import os
import random
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score

from xgboost import XGBClassifier

# -------------------------
# Reproducibility
# -------------------------
os.environ["PYTHONHASHSEED"] = str(42)
random.seed(42)
np.random.seed(42)

# --------------------
# Our split
# --------------------
train = pd.read_csv("/content/train.csv")  # adjust path if needed
y = train["hospital_death"]
X = train.drop(columns=["hospital_death"])
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=None
)

# ===============================
# Handle categorical columns
# ===============================
cat_cols = X_train.select_dtypes(include=["object"]).columns

for col in cat_cols:
    le = LabelEncoder()

    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)

    le.fit(X_train[col])

    # Add unknown token for safety
    le.classes_ = np.append(le.classes_, "__UNK__")

    X_train[col] = le.transform(X_train[col])
    X_test[col] = X_test[col].apply(
        lambda x: x if x in le.classes_ else "__UNK__"
    )
    X_test[col] = le.transform(X_test[col])

# ===============================
# Drop ID column
# ===============================
X_train = X_train.drop(columns=["encounter_id"])
X_test = X_test.drop(columns=["encounter_id"])

# ===============================
# XGBoost model
# ===============================
model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=42,
    n_jobs=1
)

# ===============================
# Train
# ===============================
model.fit(X_train, y_train)

# ===============================
# Evaluate on test set
# ===============================
print(f"Test ROC-AUC: {roc_auc_score(y_test, model.predict_proba(X_test)[:, 1]):.5f}")