# -*- coding: utf-8 -*-
"""fin_2_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4nphcHTObn2abr3vI-EaXJgwQIcL4B-
"""

import os
import random
import numpy as np
import tensorflow as tf


# Set all random seeds for reproducibility
def set_seeds(seed=42):
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

set_seeds(42)

# -------------------------------
# Strong RMSE Baseline
# Financial Engineering Competition 2/3
# -------------------------------

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Normalization
from tensorflow.keras.optimizers import Adam

# -------------------------------
# Load Data
# -------------------------------
train = pd.read_csv("/content/train.csv")  # adjust path if needed

# -------------------------------
# Prepare data for col_5 prediction
# -------------------------------
target = 'col_5'
features_col5 = ['col_1', 'col_2', 'col_3', 'col_4', 'col_6', 'col_7']
X = train[features_col5]
y = train[target]

# Split
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# -------------------------------
# Normalize features
# -------------------------------
normalizer = Normalization()
normalizer.adapt(np.array(X_train))

# -------------------------------
# Define RMSE metric
# -------------------------------
def rmse(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_true - y_pred)))

# -------------------------------
# Build Neural Network
# -------------------------------
model = Sequential([
    normalizer,
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)  # Regression output
])
model.compile(
    optimizer=Adam(0.001),
    loss='mean_squared_error',  # MSE aligns with RMSE
    metrics=[rmse]
)

model.summary()

# -------------------------------
# Train Model
# -------------------------------
history = model.fit(
    X_train, y_train,
    batch_size=256,
    epochs=100,
    verbose=1
)

# -------------------------------
# Get metric
# -------------------------------
print(f"RMSE results : {rmse(y_val, model.predict(X_val, verbose=0).flatten()).numpy():.5f}")