default_kwargs: &default_kwargs
  data_dir: /home/data/
  dataset_dir: /home/data/
  desc_file: /home/instructions.txt
  exp_name: bench
  agent.search.max_debug_depth: 20
  agent.search.debug_prob: 1
  agent.expose_prediction: True

kwargs_type: omegaconf
start: aide/start.sh
kwargs:
  <<: *default_kwargs
  agent.code.model: deepseek/deepseek-r1-0528
  agent.code.temp: 0.5
  agent.feedback.model: gpt-4.1-mini
  agent.feedback.temp: 0.5
env_vars:
  STEP_LIMIT: 500
  TIME_LIMIT_SECS: 10800
  # http_proxy: "*"
  # https_proxy: "*"
  CODE_BASE_URL: ${{ secrets.CODE_BASE_URL }}
  CODE_API_KEY: ${{ secrets.CODE_API_KEY }}
  FEEDBACK_BASE_URL: ${{ secrets.FEEDBACK_BASE_URL }}
  FEEDBACK_API_KEY: ${{ secrets.FEEDBACK_API_KEY }}
